### PR TITLE
Issues update userController and httpCodes 

### LINKED ISSUE #26: Update httpCodes and  usersController
**bug report  Solution**
1. **usersController** 

const { OK , BAD_REQUEST } = require('../constants/httpCodes');

res.status(OK).send('Fue Dado de Baja exitosamente! Hasta Pronto!');

badLine

2.  **httpCodes** 

const HTTP_CODES = {
  OK: 200,
  BAD_REQUEST: 400,
};

module.exports = HTTP_CODES;

### PR DESCRIPTION
**Pull request by lrlichardi**
1. **Summary**

> change import for Require in userController and update destroy method
user

> update httpCodes

### CODE REVIEW

File: controllers/usersController.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 const User = require('../models/user');
-import { OK , BAD_REQUEST } from '../constants/httpCodes';
+const { OK , BAD_REQUEST } = require('../constants/httpCodes');
 
 exports.deleteUser = async (req, res) => {
   try {
```
Comment (AndresHense) [inline controllers/usersController.js:5]: tira error User.destroy function doesn't exist, cambiar la linea de abajo por
`await db.User.destroy({`
y el require por
`cost db = require('../models')`

Comment (lrlichardi) [reply controllers/usersController.js:5]: ya lo miro

**Review by Galaeno — APPROVED** [review]
